# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_auto_20171201_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='author',
            new_name='added_by',
        ),
    ]
