# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171130_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Levels',
        ),
        migrations.RenameField(
            model_name='levels',
            old_name='level',
            new_name='name',
        ),
    ]
