# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20171130_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='levels',
            name='slug',
            field=models.SlugField(default='SOME STRING', unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Levels'),
        ),
    ]
