# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171130_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='slug',
        ),
    ]
