# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chungtai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chungtai.Level')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chungtai.Class'),
            preserve_default=False,
        ),
    ]
