# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungtai', '0003_auto_20171130_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateField(),
        ),
    ]
