# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chungtai', '0007_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chungtai.Volunteer'),
        ),
    ]
